import Navbar from "./navbar";
import "./globals.css";
import { icons } from "lucide-react";

export const metadata = {
  title: "Study Case Google DGoC UGM",
  description: "Generated by create next app",
  icons: "/gdsc-logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
